### ISSUE TITLE
Cody's custom command management

### ISSUE THREAD

**Issue by mnismt** [mnismt/codyplusplus#1]
## Problem

At the moment, Cody allows users to create their own custom commands by editing the configuration JSON file or using the command builder within the VS Code editor: https://sourcegraph.com/docs/cody/capabilities/commands#custom-commands

However, both approaches are relatively hard when creating complex prompts, especially when users attempt to apply some advanced techniques such as few-shot prompting or chain-of-thought.

## Goal

- To create a better UI for writing prompts with Cody's configuration properties (mode, context, etc).
- Enable users to add, edit and remove any prompt from the workspace settings or global settings.

## Proposed Solution

<a href="https://app.eraser.io/workspace/fYSv0g2qNrmCyRL9H7LR?elements=OIAKqQroZSX0JotltciMFg">Configuration properties<br /><img src="https://app.eraser.io/workspace/fYSv0g2qNrmCyRL9H7LR/preview?elements=OIAKqQroZSX0JotltciMFg&type=embed" /></a>

[Wireframe![](https://app.eraser.io/workspace/fYSv0g2qNrmCyRL9H7LR/preview?elements=fkn0cYaLop_dr1Gh2ONluA&type=embed)](https://app.eraser.io/workspace/fYSv0g2qNrmCyRL9H7LR?elements=fkn0cYaLop_dr1Gh2ONluA)

## Tasks

- [x] Read & parse the `.cody.json` file in `.vscode` the folder as an array of commands.
- [x] Check the ability to edit & remove a command in the `cody.json` file.
- [x] Create a service to CRUD custom commands.
- [x] Create the main webview for Cody++.
    - [x] List all available commands.
    - [x] "Add New" button.
- [x] Create the page for creating a new custom command.
- [x] Add the edit and trash icon in the commands list & add navigating.
- [x] Reuse the create custom commands page for editing command.
- [x] Delete command: display a modal to warn users before deleting a command (can be turned off).

**Comment by mnismt** [comment]
Creating a custom command page's wireframe:

![image](https://github.com/mnismt/codyplusplus/assets/27861064/c362a18a-4e87-46c9-9445-87e5e195a15c)

**Comment by mnismt** [comment]
This issue is closed after merging #3.
